[32mINFO    [0m moesk.tests_api.utils.api:api.py:27 TEST: Login with user@user.user, !Q2w3e4r5t credentials
[1m[31mERROR   [0m moesk.tests_api.utils.api:api.py:28 errors