{"name": "test_login_existing_user", "status": "broken", "statusDetails": {"message": "KeyError: 'db_host'", "trace": "self = <moesk.tests_ui.tests.test_login_page.TestLoginExistingUser testMethod=test_login_existing_user>\n\n    def setUp(self):\n        \"\"\"\n        Действия перед выполнением тестов:\n        - парсим config.ini,\n        - создаем соединение с БД,\n        - создаем класс с пользовательскими тестовыми данными\n        \"\"\"\n        super(BasePage, self).setUp()\n    \n        config = Config()\n        # For global environment use config['GLOBAL']\n        env = config[self.env.upper()]  # Берем значение заданного окружения (TEST, PRODUCTION, etc)\n    \n        self.app_url = env['app_url']\n    \n        # Создание соединения с БД\n>       db_credentials = DBModel(env['db_host'],\n                                 env['db_username'],\n                                 env['db_password'],\n                                 env['db_schema'],\n                                 int(env['db_port']))\nE       KeyError: 'db_host'\n\ntests_ui\\pages\\base_page.py:34: KeyError"}, "description": "\n        Авторизация под существующим пользователем и\n        и проверка нахождения на главной странице ЛК\n        ", "start": 1580111027692, "stop": 1580111031705, "uuid": "75976662-7445-4a31-b033-0ca030d11504", "historyId": "45fe1bec4d06361a86a2e8826ab10fa9", "testCaseId": "7086bef3d8dfa319e215b461bdfeddaa", "fullName": "tests_ui.tests.test_login_page.TestLoginExistingUser#test_login_existing_user", "labels": [{"name": "tag", "value": "existing_user"}, {"name": "parentSuite", "value": "tests_ui.tests"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLoginExistingUser"}, {"name": "host", "value": "LoshmanovNA-PC"}, {"name": "thread", "value": "19572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests_ui.tests.test_login_page"}]}